apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-deployment
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:latest
        ports:
        - containerPort: 9042
        env:
        - name: CASSANDRA_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: cassandra-secret
              key: username
        - name: CASSANDRA_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cassandra-secret
              key: password

---

apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042