apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: httpd:latest
        ports:
        - containerPort: 80
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: cassandra-secret
              key: username
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: cassandra-secret
              key: password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: cassandra-config
              key: cassandra-url

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100